### ISSUE TITLE
proje bilgilendirmesi

### ISSUE THREAD

**Issue by beyza-03** [bilalyarmaci/kuafor-randevu-sistemi#1]

**Comment by bilalyarmaci** [comment]
Admin maili: admin@kuafor.com
Admin şifresi: adminatkuaforpass1234

**Comment by beyza-03** [comment]
Teşekkürler 🙂

25 Kas 2024 Pzt, saat 22:56 tarihinde Bilal Yarmacı <
***@***.***> şunu yazdı:
